

command /shop:
	trigger:
		shop(1, player)

function shop(n: number, p: player):
	if {_n} = 1:
		create a new gui with virtual chest inventory with 3 rows named "Shop Menu":
			loop 36 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 10 with grass block named "&b&lBLOCKS" with lore "&fClick here to open!":
				shop(2, {_p})
			format gui slot 11 with wheat named "&b&lFARMING" with lore "&fClick here to open!":
				shop(3, {_p})
			format gui slot 12 with redstone dust named "&b&lREDSTONE" with lore "&fClick here to open!":
				shop(4, {_p})
			format gui slot 13 with water bucket named "&b&lMISC" with lore "&fClick here to open!":
				shop(6, {_p})
			format gui slot 14 with rotten flesh named "&b&lMOB DROPS" with lore "&fClick here to open!":
				shop(7, {_p})
			format gui slot 15 with diamond named "&b&lMINERALS" with lore "&fClick here to open!":
				shop(8, {_p})
			format gui slot 16 with spawner named "&b&lSPAWNERS" with lore "&fClick here to open!":
				shop(9, {_p})
		open last gui to {_p}
	if {_n} = 2:
		create a new gui with virtual chest inventory with 5 rows named "Shop - Blocks":
			loop 60 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 40 with barrier named "&cBack" with lore " " and "&7Click to return to the main menu":
				shop(1, {_p})
			format gui slot 10 with grass block named "&b&LGRASS BLOCKS" with lore "&7", "&bCOST &8| &f$%format(150, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 150, 16, grass block)
			format gui slot 11 with dirt named "&b&LDIRT" with lore "&7", "&bCOST &8| &f$%format(150, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 150, 16, dirt)
			format gui slot 12 with cobblestone named "&b&lCOBBLESTONE" with lore "&7", "&bCOST &8| &f$%format(100, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 100, 16, cobblestone)
			format gui slot 13 with oak log named "&b&lOAK LOGS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, oak log)
			format gui slot 14 with spruce log named "&b&lSPRUCE LOGS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, spruce log)
			format gui slot 15 with birch log named "&b&lBIRCH LOGS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, birch log)
			format gui slot 16 with sand named "&b&lSAND" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, sand)
			format gui slot 19 with oak leaves named "&b&lOAK LEAVES" with lore "&7", "&bCOST &8| &f$%format(1250, 2)%", "&bAMOUNT &8| &fx64","&7" and "&7Click to purchase.":
				shopbuy({_p}, 1250, 64, oak leaves)
			format gui slot 20 with smooth stone named "&b&lSMOOTH STONE" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx8","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 8, smooth stone)
			format gui slot 21 with glass named "&b&LGLASS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, glass)
			format gui slot 22 with white wool named "&b&lWOOL" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx32","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 32, white wool)
			format gui slot 23 with bricks named "&b&lBRICKS" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, bricks)
			format gui slot 24 with quartz named "&b&lQUARTZ" with lore "&7", "&bCOST &8| &f$%format(1250, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 1250, 16, quartz)
			format gui slot 25 with glowstone named "&b&lGLOWSTONE" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, glowstone)
			format gui slot 28 with sea lantern named "&b&lSEA LANTERNS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, sea lantern)
			format gui slot 29 with clay named "&b&lCLAY" with lore "&7", "&bCOST &8| &f$%format(150, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 150, 16, clay)
			format gui slot 30 with sponge named "&b&lSPONGE" with lore "&7", "&bCOST &8| &f$%format(15000, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 15000, 1, sponge)
			format gui slot 31 with soul sand named "&b&lSOUL SAND" with lore "&7", "&bCOST &8| &f$%format(5000, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 5000, 16, soul sand)
			format gui slot 32 with ice named "&b&lICE" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, ice)
			format gui slot 33 with packed ice named "&b&lPACKED ICE" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, packed ice)
			format gui slot 34 with beacon named "&b&lBEACON" with lore "&7", "&bCOST &8| &f$%format(250000, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250000, 1, beacon)

		open last gui to {_p}
	if {_n} = 3:
		create a new gui with virtual chest inventory with 5 rows named "Shop - Farming":
			loop 60 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 10 with wheat named "&b&lWHEAT" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 4, wheat)
			format gui slot 11 with cactus named "&b&lCACTUS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 4, cactus)
			format gui slot 12 with carrot named "&b&lCARROT" with lore "&7", "&bCOST &8| &f$%format(350, 2)%", "&bAMOUNT &8| &fx4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 350, 4, carrot)
			format gui slot 13 with potato named "&b&lPOTATO" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 4, potato)
			format gui slot 14 with melon slice named "&b&lMELON SLICE" with lore "&7", "&bCOST &8| &f$%format(200, 2)%", "&bAMOUNT &8| &fx8","&7" and "&7Click to purchase.":
				shopbuy({_p}, 200, 8, melon slice)
			format gui slot 15 with sugar cane named "&b&lSUGAR CANE" with lore "&7", "&bCOST &8| &f$%format(1250, 2)%", "&bAMOUNT &8| &fx16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 1250, 16, sugar cane)
			format gui slot 16 with pumpkin named "&b&lPUMPKIN" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 1, pumpkin)
			format gui slot 19 with melon named "&b&lMELON" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 1, melon)
			format gui slot 20 with pumpkin seeds named "&b&lPUMPKIN SEEDS" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 1, pumpkin seeds)
			format gui slot 21 with melon seeds named "&b&lMELON SEEDS" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 1, melon seeds)
			format gui slot 22 with seeds named "&b&lSEEDS" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &fx1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 1, seeds)
			format gui slot 40 with barrier named "&cBack" with lore " " and "&7Click to return to the main menu":
				shop(1, {_p})
		open last gui to {_p}
	if {_n} = 4:
		create a new gui with virtual chest inventory with 5 rows named "Shop - Redstone":
			loop 60 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 10 with redstone named "&b&lREDSTONE" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, redstone)
			format gui slot 11 with redstone torch named "&b&lREDSTONE TORCH" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, redstone torch)
			format gui slot 12 with redstone repeater named "&b&lREDSTONE REPEATER" with lore "&7", "&bCOST &8| &f$%format(750, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 750, 4, redstone repeater)
			format gui slot 13 with redstone comparator named "&b&lREDSTONE COMPARATOR" with lore "&7", "&bCOST &8| &f$%format(750, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 750, 4, redstone comparator)
			format gui slot 14 with piston named "&b&lPISTON" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 4, piston)
			format gui slot 15 with sticky piston named "&b&lSTICKY PISTON" with lore "&7", "&bCOST &8| &f$%format(750, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, sticky piston)
			format gui slot 16 with observer named "&b&lOBSERVER" with lore "&7", "&bCOST &8| &f$%format(5000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 5000, 1, observer)
			format gui slot 19 with lever named "&b&lLEVER" with lore "&7", "&bCOST &8| &f$%format(50, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 50, 1, lever)
			format gui slot 20 with stone button named "&b&lSTONE BUTTON" with lore "&7", "&bCOST &8| &f$%format(50, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 50, 1, stone button)
			format gui slot 40 with barrier named "&cBack" with lore " " and "&7Click to return to the main menu":
				shop(1, {_p})
		open last gui to {_p}
	if {_n} = 6:
		create a new gui with virtual chest inventory with 5 rows named "Shop - Misc":
			loop 60 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 10 with water bucket named "&b&lWATER" with lore "&7", "&bCOST &8| &f$%format(100, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 100, 1, water bucket)
			format gui slot 11 with lava bucket named "&b&lLAVA" with lore "&7", "&bCOST &8| &f$%format(100, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 100, 1, lava bucket)
			format gui slot 12 with chest named "&b&lCHEST" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, chest)
			format gui slot 13 with oak sign named "&b&lSIGN" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, oak sign)
			format gui slot 14 with bone meal named "&b&lBONE MEAL" with lore "&7", "&bCOST &8| &f$%format(1250, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 1250, 16, bone meal)
			format gui slot 15 with ladder named "&b&lLADDER" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 16, ladder)
			format gui slot 16 with hopper named "&b&lHOPPER" with lore "&7", "&bCOST &8| &f$%format(2000, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 2000, 16, hopper)
			format gui slot 19 with experience bottle named "&b&lXP BOTTLES" with lore "&7", "&bCOST &8| &f$%format(2000, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 2000, 16, experience bottle)
			format gui slot 40 with barrier named "&cBack" with lore " " and "&7Click to return to the main menu":
				shop(1, {_p})
		open last gui to {_p}
	if {_n} = 7:
		create a new gui with virtual chest inventory with 5 rows named "Shop - Mob Drops":
			loop 60 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 10 with bone named "&b&lBONE" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 1, bone)
			format gui slot 11 with rotten flesh named "&b&lROTTEN FLESH" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 4, rotten flesh)
			format gui slot 12 with string named "&b&lSTRING" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f2","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 2, string)
			format gui slot 13 with leather named "&b&lLEATHER" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 4, leather)
			format gui slot 14 with gunpowder named "&b&lGUNPOWDER" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f2","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 2, gunpowder)
			format gui slot 15 with egg named "&b&lEGGS" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 4, egg)
			format gui slot 16 with feather named "&b&lFEATHER" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f2","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 2, feather)
			format gui slot 19 with slime ball named "&b&lSLIME BALL" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f4","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 4, slime ball)
			format gui slot 20 with blaze rod named "&b&lBLAZE ROD" with lore "&7", "&bCOST &8| &f$%format(250, 2)%", "&bAMOUNT &8| &f2","&7" and "&7Click to purchase.":
				shopbuy({_p}, 250, 2, blaze rod)
			format gui slot 40 with barrier named "&cBack" with lore " " and "&7Click to return to the main menu":
				shop(1, {_p})
		open last gui to {_p}
	if {_n} = 8:
		create a new gui with virtual chest inventory with 5 rows named "Shop - Minerals":
			loop 60 times:
				format gui slot ( loop-number - 1 ) with gray stained glass pane named "&7" 
			format gui slot 10 with coal named "&b&lCOAL" with lore "&7", "&bCOST &8| &f$%format(150, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 150, 1, coal)
			format gui slot 11 with iron ingot named "&b&lIRON" with lore "&7", "&bCOST &8| &f$%format(275, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 275, 1, iron ingot)
			format gui slot 12 with lapis named "&b&lLAPIS" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, lapis)
			format gui slot 13 with redstone named "&b&lREDSTONE" with lore "&7", "&bCOST &8| &f$%format(500, 2)%", "&bAMOUNT &8| &f16","&7" and "&7Click to purchase.":
				shopbuy({_p}, 500, 16, redstone)
			format gui slot 14 with gold ingot named "&b&lGOLD" with lore "&7", "&bCOST &8| &f$%format(600, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 600, 1, gold ingot)
			format gui slot 15 with diamond named "&b&lDIAMOND" with lore "&7", "&bCOST &8| &f$%format(1250, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 1250, 1, diamond)
			format gui slot 16 with emerald named "&b&lEMERALD" with lore "&7", "&bCOST &8| &f$%format(1500, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				shopbuy({_p}, 1500, 1, emerald)
			format gui slot 40 with barrier named "&cBack" with lore " " and "&7Click to return to the main menu":
				shop(1, {_p})
		open last gui to {_p}
	if {_n} = 9:
		{_p} command "spawnershop"
		
command /spawnershop:
	trigger:
		create a new gui with virtual chest inventory with 3 rows named "Shop - Spawners":
			format gui slot (integers between 0 and 26) with black stained glass pane named "&f"
			format gui slot 10 with spawner named "&b&lPIG SPAWNER" with lore "&7", "&bCOST &8| &f$%format(50000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				buySpawner(player, 50000, "Pig")
			format gui slot 11 with spawner named "&b&lZOMBIE SPAWNER" with lore "&7", "&bCOST &8| &f$%format(150000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				buySpawner(player, 150000, "Zombie")
			format gui slot 12 with spawner named "&b&lSKELETON SPAWNER" with lore "&7", "&bCOST &8| &f$%format(250000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				buySpawner(player, 250000, "skeleton")
			format gui slot 13 with spawner named "&b&lBLAZE SPAWNER" with lore "&7", "&bCOST &8| &f$%format(500000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				buySpawner(player, 500000, "blaze")
			format gui slot 15 with spawner named "&b&lVILLAGER SPAWNER" with lore "&7", "&bCOST &8| &f$%format(5000000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				buySpawner(player, 5000000, "villager")
			format gui slot 14 with spawner named "&b&lIRON GOLEM SPAWNER" with lore "&7", "&bCOST &8| &f$%format(3000000, 2)%", "&bAMOUNT &8| &f1","&7" and "&7Click to purchase.":
				buySpawner(player, 3000000, "irongolem")
		open last gui to player
	
function buySpawner(p: player, cost: integer, spawner: text):
	if {_p}'s inventory can't hold diamond sword named "ddd":
		send "&cYour inventory is full!" to {_p}
	else:
		if {stats::balance::%{_p}%} >= {_cost}:
			remove {_cost} from {stats::balance::%{_p}%}
			console command "/ss give %{_p}% %{_spawner}% 1"
			send({_p}, "&aYou have purchased a %{_spawner}%&a.", "exp")
		else:
			send({_p}, "&cYou don't have enough for this!", "bass")
		
		
		
		
		
# This basicily works as 1st is slot of gui slot, 2nd is cost, 3rd is text, 4th is amount, 5th is {_p} always keep that, and 6th is the block aka grass block or dirt whatever u want

function shopbuy(p: player, cost: number, amount: number, m: material):
	set {_u} to {_p}'s uuid
	if {stats::balance::%{_u}%} >= {_cost}:
		send title "&b&lPURCHASED" with subtitle "&fYou have purchased %{_amount}%&fx &b%{_m}%" to {_p}
		give {_p} {_amount} of {_m} 
		remove {_cost} from {stats::balance::%{_p}%}
	if {_cost} > {stats::balance::%{_p}%}:
		set {_need} to {_cost} - {stats::balance::%{_p}%}
		send "" to {_p}
		send "&b&lINVALID AMOUNT" to {_p}
		send "&fYou need atleast &b$%format({_need}, 2)% &Fmore!" to {_p}
		send "" to {_p}

on rightclick:
	if name of clicked entity is "&b&LSHOP":
		shop(1, player)
		
on rightclick:
	if name of clicked entity is "&b&lISLAND":
		make player execute command "/is"

on rightclick:
	if name of clicked entity is "&b&lPAYOUTS":
		make player execute command "/payouts"